clear 
close all
%Make Graph of Graphs
QuarantineFactor=1%[0.5 0.5;0.5 0.5];
nvar=7;%
options1 = odeset('Refine',50);
options2 = odeset(options1,'NonNegative',nvar);
N=(8.8e6);
beta0=(3/4)/24/N;
T=90*24;
%check various cases:
%beta(1,2) infections of asultd by children
%beta(2,1) infrction of children by adults
%beta(1,1) / beta(2,2) infection of adults by adults / children by children
for Case=1:5
    if Case==1
        beta=QuarantineFactor.*beta0.*[1 1;1 1]; %all the same
    elseif Case==2
        beta=QuarantineFactor.*beta0.*[1 1;0.01 1]; %childern are not so incfecting to adults
    elseif Case==3
        beta=QuarantineFactor.*beta0.*[1 1;0.01 0.01]; %childern are not so incfecting to all
    elseif Case==4
        beta=QuarantineFactor.*beta0.*[1 0.5;0.7 1]; %what we think conservativly
    elseif Case==5
        beta=QuarantineFactor.*beta0.*[1 0.5;0.7 3]; %children see 3 times more children than at home
    end
    gammaE=(1/5/24)*[1 1];
    gammaR=(1/4/24)*[1 1];
    I0=50000;
    fractionOfChildrenInfected=0.35;
    yinit=[N-0.17*N-I0,0.17*N,0,(1-fractionOfChildrenInfected)*I0,fractionOfChildrenInfected*I0,0,0];
    [t,y] = ode45(@(t,y) SEIR_modelNtwo(t,y,beta,gammaE,gammaR),[0 T],yinit);
    hold all
   % plot(t/24,y(:,5)+y(:,6),'LineWidth',2),grid on,shg
   Y(:,Case)=interp1(t,y(:,5)+y(:,6),0:0.1:T);
   tt=0:0.1:T;
end
createmyfigure(tt,Y)

new_data = csvread('C:\Users\yoel\Documents\army\corona\rami simulation\python\israel population graph virus beta=0.375 lockdown=1 23.4.20.csv');
new_random_data = csvread('C:\Users\yoel\Documents\army\corona\rami simulation\python\random gamma graph virus 22.4.20.csv');
hold on; plot((1:length(new_data(1,:)))/10, new_data(3,:)*8.8e6/(sum(new_data(:,1))),'DisplayName','israel graph')
hold on; plot((1:length(new_data(1,:)))/10, new_random_data(3,:)*8.8e6/(sum(new_data(:,1))),'DisplayName','random graph')

function createmyfigure(tt,Y)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data

%  Auto-generated by MATLAB on 24-Apr-2020 13:24:08

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(tt,Y(:,1),'DisplayName','all the same','LineWidth',2);

% Create plot
plot(tt,Y(:,2),'DisplayName','kids dont infect adults','LineWidth',2);

% Create plot
plot(tt,Y(:,3),'DisplayName','kids dont infect anyone','LineWidth',2);

% Create plot
plot(tt,Y(:,4),'DisplayName','conservative opinion','LineWidth',2);

% Create plot
plot(tt,Y(:,5),'DisplayName','kids see three time many people',...
    'LineWidth',2);

% Create ylabel
ylabel('Infected');

% Create xlabel
xlabel('Days');

grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',11);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.52288961038961 0.793175146771033 0.374675324675325 0.121575342465753],...
    'FontSize',11);


end
