function dydt = SEIR_modelNtwo(t,y,beta,gammaE,gammaR)
 %dydt = SEIR_modelSchools(t,y,beta_pp,beta_cp,beta_pc,beta_cc,gammaEp,gammaEc,gammaRp,gammaRc,gammaH,gammaHR,gammaD,pp,pc)
%y=[Sp,Sc,Ep,Ec,Ip,Ic,R]
%y(1)=Sp
%y(2)=Sc
%y(3)=Ep
%y(4)=Ec
%y(5)=Ip
%y(6)=Ic;
%y(7)=R;
dydt=[-beta(1,1)*y(5)*y(1)-beta(2,1)*y(6)*y(1),...
    -beta(1,2)*y(5)*y(2)-beta(2,2)*y(6)*y(2),...
    beta(1,1)*y(5)*y(1)+beta(2,1)*y(6)*y(1)-gammaE(1)*y(3),...
    beta(1,2)*y(5)*y(2)+beta(2,2)*y(6)*y(2)-gammaE(2)*y(4),...
    gammaE(1)*y(3)-gammaR(1)*y(5),...
    gammaE(2)*y(4)-gammaR(2)*y(6),...
    gammaR(1)*y(5)+gammaR(2)*y(6)].';

