% each simulation has the following parameters:
% 
nameList = ["correlation","pop","SB","SnB","nSnB","nSB","PartSick","peakHosp",...
    "Dead","peakInf","peakInfTime","infSB","infSnB","infnSnB","infnSB",...
    "R0Manual","R0Growth","adjRsquaredR0","freq","dataLocation","Tspan",...
    "NumPeople","beta","gamma","alpha","graphType","pCautious","pRisk",...
    "pHosp","pDead","gammaHosp","configLocation","simulationType"];

SimResults  = cell2table(cell(0,length(nameList)),...
    'VariableNames', nameList);